export const HANDLE_LOGIN_USER = 'HANDLE_LOGIN_USER';
export const HANDLE_LOGOUT_USER = 'HANDLE_LOGOUT_USER';

export const GET_USER_INFO_REQUEST = 'GET_USER_INFO_REQUEST';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_FAIL = 'GET_USER_INFO_FAIL';

export const GET_MAIN_MENU_REQUEST = 'GET_MAIN_MENU_REQUEST';
export const GET_MAIN_MENU_SUCCESS = 'GET_MAIN_MENU_SUCCESS';
export const GET_MAIN_MENU_ERROR = 'GET_MAIN_MENU_ERROR';

export const GET_CLASSES_REQUEST = 'GET_CLASSES_REQUEST';
export const GET_CLASSES_SUCCESS = 'GET_CLASSES_SUCCESS';
export const GET_CLASSES_ERROR = 'GET_CLASSES_ERROR';

export const GET_SUBJECT_REQUEST = 'GET_SUBJECT_REQUEST';
export const GET_SUBJECT_SUCCESS = 'GET_SUBJECT_SUCCESS';
export const GET_SUBJECT_ERROR = 'GET_SUBJECT_ERROR';

export const GET_SUBJECT_VIA_CLASSES_REQUEST = 'GET_SUBJECT_VIA_CLASSES_REQUEST';
export const GET_SUBJECT_VIA_CLASSES_SUCCESS = 'GET_SUBJECT_VIA_CLASSES_SUCCESS';
export const GET_SUBJECT_VIA_CLASSES_ERROR = 'GET_SUBJECT_VIA_CLASSES_ERROR';

export const GET_PRICE_REQUEST = 'GET_PRICE_REQUEST';
export const GET_PRICE_SUCCESS = 'GET_PRICE_SUCCESS';
export const GET_PRICE_ERROR = 'GET_PRICE_ERROR';

export const GET_USER_DOCUMENT_REQUEST = 'GET_USER_DOCUMENT_REQUEST';
export const GET_USER_DOCUMENT_SUCCESS = 'GET_USER_DOCUMENT_SUCCESS';
export const GET_USER_DOCUMENT_ERROR = 'GET_USER_DOCUMENT_ERROR';