export const HANDLE_LOGIN_USER = 'HANDLE_LOGIN_USER';
export const HANDLE_LOGOUT_USER = 'HANDLE_LOGOUT_USER';

export const GET_USER_INFO_REQUEST = 'GET_USER_INFO_REQUEST';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_FAIL = 'GET_USER_INFO_FAIL';
